name: Process Build Artifact

on:
  repository_dispatch:
    types: [build_artifact_trigger]

jobs:
  process-build-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log and download artifact
        run: |
          echo "Received artifact_url: ${{ github.event.client_payload.artifact_url }}"
          curl -o build.tar.gz ${{ github.event.client_payload.artifact_url }}
          mkdir -p xedBuild
          tar -xf build.tar.gz -C xedBuild
          bash $PWD/.github/workflows/update.sh $PWD/xedBuild
          curl -o android.jar "https://raw.githubusercontent.com/Sable/android-platforms/master/android-35/android.jar"
          mv android.jar libs
          rm -rf .gradle
          chmod +x gradlew
          ./gradlew shadowJar
          ls
          ls output
          du -h output
