name: Process Build Artifact

on:
  repository_dispatch:
    types: [build_artifact_trigger]

jobs:
  process-build-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log and download artifact
        run: |
          echo "Received artifact_url: ${{ github.event.client_payload.artifact_url }}"
          curl -o build.tar.gz ${{ github.event.client_payload.artifact_url }}
          mkdir -p xedBuild
          tar -xf build.tar.gz -C xedBuild
          bash $PWD/.github/workflows/update.sh $PWD/xedBuild
          rm -rf .gradle
          chmod +x gradlew
          ./gradlew shadowJar
          ls
          ls output
          du -h output
          mv output/* xed-editor-sdk.jar

      - name: Upload xed-editor-sdk.jar
        uses: actions/upload-artifact@v4
        with:
          name: xed-editor-sdk
          path: xed-editor-sdk.jar
