name: Process Build Artifact

on:
  repository_dispatch:
    types: [build_artifact_trigger]

jobs:
  process-build-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log and download artifact
        run: |
          echo "Received artifact_url: ${{ github.event.client_payload.artifact_url }}"
          curl -o build.tar.gz ${{ github.event.client_payload.artifact_url }}
          mkdir -p xedBuild
          tar -xf build.tar.gz -C xedBuild
          bash $PWD/.github/workflows/update.sh $PWD/xedBuild
          curl -o android.jar "https://raw.githubusercontent.com/Sable/android-platforms/master/android-35/android.jar"
          mv android.jar libs
          rm -rf .gradle
          chmod +x gradlew
          ./gradlew shadowJar
          ls
          ls output
          du -h output

          curl bashupload.com -T output/* > output.txt

          ARTIFACT_URL=$(grep -oE '(http|https)://[^ ]+' output.txt | head -n 1)

          if [[ -z "$ARTIFACT_URL" ]]; then
            echo "Error: Failed to extract artifact URL."
            exit 1
          fi


          PAYLOAD=$(jq -n \
            --arg url "$ARTIFACT_URL" \
            '{event_type: "upload_artifact_trigger", client_payload: {artifact_url: $url}}')

          echo "Payload to be sent:"
          echo "$PAYLOAD"

          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.UPLOAD_SDK_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD" \
            https://api.github.com/repos/Xed-Editor/Xed-Editor/dispatches
      
