name: Process Build Artifact

on:
  repository_dispatch:
    types: [build_artifact_trigger]

jobs:
  process-build-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log payload
        run: |
          echo "Received artifact_url: ${{ github.event.client_payload }}"
